### ISSUE TITLE
waylayGetMetadata:1.0.0 logs too much

### ISSUE THREAD

**Issue by francisdb** [waylayio/Sensors#47]
We really should avoid logging whole axios responses

```
2022-02-23T11:15:49.588897Z 00000005239c INFO  Node node_1[dice:1.0.2] executed with state: SIX
2022-02-23T11:15:49.624213Z 00000000af88 DEBUG Node waylayGetMetadata[waylayGetMetadata:1.0.0] 2022-02-23T11:15:49.618Z INFO { Error: Request failed with status code 404
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url: 'https://staging.waylay.io/api/resources/151DF-ENG-18',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'waylay-js',
        Authorization:
         'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZjY2M4ODQzLWQ3OGQtNDllOC04NGM0LTM3MzRhNGFmOTkyOSJ9.eyJ0ZW5hbnQiOiI2Y2NjODg0My1kNzhkLTQ5ZTgtODRjNC0zNzM0YTRhZjk5MjkiLCJkb21haW4iOiJzdGFnaW5nLndheWxheS5pbyIsImxpY2Vuc2VzIjpbInRzYW5hbHl0aWNzIiwibXF0dG1hbmFnZXIiLCJyYmFjIl0sImV4cCI6MTY0NTYyNDQzNSwiaWF0IjoxNjQ1NTgxMjM1LCJpc3MiOiJAd2F5bGF5L2F1dGgiLCJzdWIiOiJhcHBsaWNhdGlvbnMvZjNlM2YxM2ItODU4ZS00ODcxLWE1OTItOWQyODBjZjliMTA4In0.zkJ_pmMrOirh09UvgpiXVuglkmyI8KV15dCj-NKMACgfRM2vLd_Y6OvqV5gkQpF21VQ2SaU8cTNZoriDA4EFeeMT7XwbMpd47tQlD8HjVYC8KaXLCizQlX25NgFuMDa-WaP88WbPYUDAHTIsTpz2qdV-2C51ESZdFq5OMnBMX9glMt1haSjUexP9qwiAjBHi592-RL_Q4jacL4Rmjmb5IGDfNeBK9Kkj9qG4eF5m1L5L6_A7Lsh3Za9lFe9Y8JtCx8Ew_YIT75J4kBQYiOCihWBio1uxHhK1uKP3e10g1eUZ3z3v8gEW2Z-BFTW5uznyljRdOreA6rCpiZRzMqvM9w' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     paramsSerializer: [Function: paramsSerializer],
     timeout: NaN,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     path: '/api/resources/151DF-ENG-18',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'staging.waylay.io',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'staging.waylay.io',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 738716,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'staging.waylay.io',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'staging.waylay.io',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
    …
2022-02-23T11:15:49.624215Z 00000000af88 DEBUG Node waylayGetMetadata[waylayGetMetadata:1.0.0] rawData = {}
2022-02-23T11:15:49.624218Z 00000000af88 INFO  Node waylayGetMetadata[waylayGetMetadata:1.0.0] executed with state: Not Collected

```

**Comment by francisdb** [comment]
looks like this plugin is not a standard plugin

**Comment by francisdb** [comment]
This is still the case with the new version

see #46 for a cleaner solution
```
console.error(error)
```
