### ISSUE TITLE
condition node cannot deal with ${?nodes.bla.rawdata.x}

### ISSUE THREAD

**Issue by tovleeuw** [waylayio/Sensors#55]
trying to define a condition like this that should result in a comparison of 5 != null which is true
<img width="595" alt="image" src="https://user-images.githubusercontent.com/38496857/156651331-1c0f5115-1912-4b2b-8d3e-050363add154.png">

but getting this error
2022-03-03T20:55:20.868486Z     6387     DEBUG Node condition_1[condition:1.1.6] 2022-03-03T20:55:20.868Z INFO SyntaxError: Unexpected end of input
    at script (/app/function/index.js:74:30)
    at Promise (/app/function/index.js:62:5)
    at new Promise (<anonymous>)
    at module.exports (/app/function/index.js:53:10)
    at middleware (/app/index.js:43:26)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
2022-03-03T20:55:20.868488Z     6387     WARN  Node condition_1[condition:1.1.6] execution failed: [SyntaxError: Unexpected end of input]

**Comment by francisdb** [comment]
${?...} resolves to empty string if the value is not found. $${? } will probably do the same, need to check. We could maybe improve this if we know the result is supposed to be a script.
